// Đăng nhập
export const POST_LOGIN_REQUEST = "POST_LOGIN_REQUEST"
export const POST_LOGIN_SUCCESS = "POST_LOGIN_SUCCESS"
export const POST_LOGIN_FAILTURE = "POST_LOGIN_FAILTURE"
// Đăng ký
export const POST_SIGNIN_REQUEST = "POST_SIGNIN_REQUEST"
export const POST_SIGNIN_SUCCESS = "POST_SIGNIN_SUCCESS"
export const POST_SIGNIN_FAILTURE = "POST_SIGNIN_FAILTURE"