// Lấy thông tin hệ thống rạp
export const GET_CINEMABRAND_REQUEST = "GET_CINEMABRAND_REQUEST"
export const GET_CINEMABRAND_SUCCESS = "GET_CINEMABRAND_SUCCESS"
export const GET_CINEMABRAND_FAILTURE = "GET_CINEMABRAND_FAILTURE"
// Lấy thông tin cụm rạp
export const GET_THEATER_REQUEST = "GET_THEATER_REQUEST"
export const GET_THEATER_SUCCESS = "GET_THEATER_SUCCESS"
export const GET_THEATER_FAILTURE = "GET_THEATER_FAILTURE"
// Lấy thông tin lịch chiếu theo rạp
export const GET_SCHEDULE_REQUEST = "GET_SCHEDULE_REQUEST"
export const GET_SCHEDULE_SUCCESS = "GET_SCHEDULE_SUCCESS"
export const GET_SCHEDULE_FAILTURE = "GET_SCHEDULE_FAILTURE"
// Lấy thông tin phòng vé
export const GET_SLOTS_REQUEST = "GET_SLOTS_REQUEST"
export const GET_SLOTS_SUCCESS = "GET_SLOTS_SUCCESS"
export const GET_SLOTS_FAILTURE = "GET_SLOTS_FAILTURE"
// Đặt vé
export const BOOKING_REQUEST = "BOOKING_REQUEST"
export const BOOKING_SUCCESS = "BOOKING_SUCCESS"
export const BOOKING_FAILTURE = "BOOKING_FAILTURE"